### ISSUE TITLE
I can add a page and be editing it in the preview

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#11]
plone currently allows for editing before creation.

Instead
- [ ] click add Page will ask the user for the tiile and optional description
   - if this is too hard we can just create page1, page2 etc? The user can still rename inside the page via shortname
- [ ] creates the page via api
- [ ] route to the view page (or edit mode on that page once working)

This is mockup for adding a folder but maybe we do page the same way?

![Image](https://github.com/collective/volto-hydra/assets/41700/a6c6556b-8ab7-44ba-8517-40fc0e845eb8)

![Image](https://github.com/collective/volto-hydra/assets/41700/9b4a0280-c0fc-4a56-bb1b-f5c64f61b50e)

**Comment by djay** [comment]
As discussed
- creating a UUID for page shortname/id is probably easiest. You click add and then it creates the page and redirects to the edit.
   - pros
      - feels like normal plone workflow
      - can change the UUID to be a based on title after the first save later. 
   - cons
      - will have to deal with cancel
- OR: change the add page to always display the form view on add
   - Then you enter a title and shortname and click save. Save will then redirect you the full edit page
   - pros
      - you can to pick a title before any transaction happens and never left with bad url
    - cons
      - not like plone now. you get an extra screen

**Comment by MAX-786** [comment]
> OR: change the add page to always display the form view on add
> 
> * Then you enter a title and shortname and click save. Save will then redirect you the full edit page
> * should be easy to do. just change the condition so it appears even if blocks enabled, but only on add view, not edit
> * pros
>   
>   * you can to pick a title before any transaction happens and never left with bad url
> * cons
>   
>   * not like plone now. you get an extra screen

I looked into this approach and one way was to have Custom Form whenever user go to '/add' endpoint. 

But after looking into volto core I found that this [visual prop](https://github.com/plone/volto/blob/4a2da78222550bb06c2abc7b5f0c803f0f5c391c/packages/volto/src/components/manage/Add/Add.jsx#L260) is passed by Edit and Add views to tell the Form whether to show the Sidebar and Blocks or not. 

So, I just changed this `visual` prop in Add view to be false always since we are not rendering Blocks and so now Add view shows the Form like it does when adding a File where you can give this page a title and summary and once you click save it will redirect you to that page and you can further edit it. Also cancel works as usual.

Till now it doesn't seems to break anything. so lemme hear what you guys say about this :).

You can look at the code and Demo video in the PR

**Comment by djay** [comment]
If possible it would be good to redirect directly to edit mode so it's closer to what plone normally does

**Comment by MAX-786** [comment]
Yeah IG we can hook into onSubmit handler to do so.
