### ISSUE TITLE
I can Click on block in blocks nav tree and edit it in sidebar , save and see it changed in preview

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#14]

**Comment by djay** [comment]
as discussed. take victors navtree code and include it in this addon to just get a very basic list of blocks. Later we can take this out and use the proper navtree that will be included in 18.

**Comment by djay** [comment]
@MAX-786 this is his latest version. We probably can't wait to have this merged but we can just copy some of the code and make a simpler version for now that list lists out the blocks

**Comment by djay** [comment]
@JeffersonBledsoe it seems like the blocks nav branch is almost finished. Would there be any problem using it as is and therefore using the latest 18 and 6.1 backend?

**Comment by djay** [comment]
Descision was to wait until the navtree is released into a 18 alpha and instead do the click on preview to select earlier #24

**Comment by djay** [comment]
Not something that needs to be solved here but seems that blocks navtree doesn't really have a good logical place in the quanta design.

Tabs are gone and instead you get a settings button


![Image](https://github.com/collective/volto-hydra/assets/41700/afdf1a72-2ca7-43b1-95a9-6f5e99819751)

and if no block settings is enabled you get no sidebar at all


![Image](https://github.com/collective/volto-hydra/assets/41700/d8f7aa5d-3384-442d-abcd-dd4923b35081)

Rather than put another button on the edit toolbar I'd suggest it appears as something that can be expanded from a block breadcrumb at the top of the block settings. And if no block is selected then this is all that shows. But then how to get to this if you can't select any block?

**Comment by djay** [comment]
@MAX-786 the order tab is now deployed but I can't see to click on a block and edit it. I'm not sure if thats something you've broken or thats just not meant to be how it works?

**Comment by MAX-786** [comment]
> @MAX-786 the order tab is now deployed but I can't see to click on a block and edit it. I'm not sure if thats something you've broken or thats just not meant to be how it works?

In volto, clicking on blocks in Order tab will select the block on screen, so I am aiming for that for the iframe. I'll create a seperate PR for that.
